import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { Button, Col, Container, Form, ListGroup, Navbar, Row } from 'react-bootstrap'
import Image from 'next/image'
import { faFloppyDisk, faPlus, faTrash } from '@fortawesome/free-solid-svg-icons'
import { useEffect, useState } from 'react'

export default function Home() {
  const apiUrl = process.env.apiUrl;
  const [notes, setNotes] = useState([]);
  const [selected, setSelected] = useState(null);

  useEffect(() => {
    fetch(apiUrl)
      .then(res => res.json())
      .then(data => setNotes(data));
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" type="image/png" href="/logo.png" />
      </Head>
      <main>
        <Navbar bg="dark" variant="dark">
          <Container>
            <Navbar.Brand>
              <Image src="/logo.png" width={30} height={30} alt="Logo" className="d-inline-block align-top" />{" "}
              KeepNote
            </Navbar.Brand>
          </Container>
        </Navbar>
        <Container className="mt-4">
          <Row>
            <Col sm="4" lg="3">
              <Button variant="primary" className="w-100">
                <FontAwesomeIcon icon={faPlus} /> New Note
              </Button>
              <ListGroup className="mt-4">
                {notes.map(note => (
                  <ListGroup.Item active={note.id == selected?.id} key={note.id} action
                    onClick={() => setSelected({ ...note })}>
                    {note.title}
                  </ListGroup.Item>
                ))}
              </ListGroup>
            </Col>
            <Col sm="8" lg="9">
              {selected &&
                <Form>
                  <Form.Group className="mb-2">
                    <Form.Control type="text" placeholder="Enter title" value={selected.title} />
                  </Form.Group>
                  <Form.Group className="mb-2">
                    <Form.Control type="text" as="textarea" rows={12} placeholder="Write something.." value={selected.content ?? ""} />
                  </Form.Group>
                  <div>
                    <Button variant="primary" className="me-2">
                      <FontAwesomeIcon icon={faFloppyDisk} />{" "}
                      Save
                    </Button>
                    <Button variant="danger">
                      <FontAwesomeIcon icon={faTrash} />{" "}
                      Delete
                    </Button>
                  </div>
                </Form>
              }
            </Col>
          </Row>
        </Container>
      </main>
    </>
  )
}
